import type { SVGProps } from 'react';
import {
  AlarmClock,
  Apple,
  ArrowLeft,
  ArrowUp,
  Ban,
  BarChart3,
  Bell,
  BellOff,
  BellRing,
  BookOpen,
  BrainCircuit,
  Calendar,
  CalendarCheck,
  Brush,
  CalendarDays,
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  ClipboardList,
  Coffee,
  Cookie,
  CircleDot,
  Clock,
  Cloud,
  Copy,
  Download,
  Eraser,
  Eye,
  EyeOff,
  Feather,
  Flag,
  FileText,
  Flame,
  Flower2,
  Folder,
  FolderOpen,
  Globe,
  Gauge,
  Gift,
  GraduationCap,
  Hand,
  Headphones,
  Heart,
  Highlighter,
  Hourglass,
  Image,
  Info,
  Key,
  Keyboard,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  Lightbulb,
  Link,
  ListChecks,
  ListTodo,
  LogOut,
  Lock,
  Medal,
  MessageCircle,
  Mic,
  Minus,
  Moon,
  Move,
  Music,
  NotebookPen,
  Palette,
  Paperclip,
  Pause,
  PawPrint,
  PenLine,
  Pencil,
  PieChart,
  Pin,
  Play,
  Printer,
  Plus,
  Rainbow,
  RefreshCcw,
  Reply,
  RotateCcw,
  Ruler,
  Scale,
  Save,
  Search,
  Send,
  Shirt,
  SkipForward,
  Settings,
  Share2,
  Shield,
  Smile,
  Smartphone,
  Sparkle,
  Sparkles,
  Sprout,
  Star,
  Sticker,
  StickyNote,
  Sun,
  Tag,
  Target,
  Timer,
  Trash2,
  TrendingUp,
  TrendingDown,
  TriangleAlert,
  Trophy,
  Type,
  Upload,
  User,
  Users,
  Volume2,
  Wand2,
  X,
  Zap,
} from 'lucide-react';

const MAP = {
  alarm: AlarmClock,
  alert: TriangleAlert,
  apple: Apple,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUp,
  barChart: BarChart3,
  bell: Bell,
  bellOff: BellOff,
  ban: Ban,
  bellRing: BellRing,
  book: BookOpen,
  brain: BrainCircuit,
  calendar: Calendar,
  calendarCheck: CalendarCheck,
  brush: Brush,
  calendarDays: CalendarDays,
  camera: Camera,
  check: Check,
  checkCircle: CheckCircle2,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  clipboard: ClipboardList,
  coffee: Coffee,
  circleDot: CircleDot,
  clock: Clock,
  cookie: Cookie,
  cloud: Cloud,
  copy: Copy,
  download: Download,
  eraser: Eraser,
  eye: Eye,
  eyeOff: EyeOff,
  feather: Feather,
  file: FileText,
  flag: Flag,
  flame: Flame,
  flower: Flower2,
  folder: Folder,
  folderOpen: FolderOpen,
  globe: Globe,
  gauge: Gauge,
  gift: Gift,
  graduation: GraduationCap,
  hand: Hand,
  headphones: Headphones,
  heart: Heart,
  highlighter: Highlighter,
  hourglass: Hourglass,
  image: Image,
  info: Info,
  key: Key,
  keyboard: Keyboard,
  layers: Layers,
  layoutDashboard: LayoutDashboard,
  leaf: Leaf,
  layoutGrid: LayoutGrid,
  lightbulb: Lightbulb,
  link: Link,
  listChecks: ListChecks,
  listTodo: ListTodo,
  logout: LogOut,
  lock: Lock,
  medal: Medal,
  message: MessageCircle,
  mic: Mic,
  minus: Minus,
  moon: Moon,
  move: Move,
  music: Music,
  notes: NotebookPen,
  palette: Palette,
  paperclip: Paperclip,
  pause: Pause,
  paw: PawPrint,
  pen: PenLine,
  printer: Printer,
  pencil: Pencil,
  pieChart: PieChart,
  pin: Pin,
  play: Play,
  plus: Plus,
  rainbow: Rainbow,
  refresh: RefreshCcw,
  reply: Reply,
  rotate: RotateCcw,
  ruler: Ruler,
  scale: Scale,
  save: Save,
  search: Search,
  send: Send,
  shirt: Shirt,
  skipForward: SkipForward,
  settings: Settings,
  share: Share2,
  shield: Shield,
  smile: Smile,
  smartphone: Smartphone,
  sparkle: Sparkle,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  sticker: Sticker,
  sticky: StickyNote,
  sun: Sun,
  tag: Tag,
  target: Target,
  timer: Timer,
  trash: Trash2,
  trend: TrendingUp,
  trendingDown: TrendingDown,
  trophy: Trophy,
  type: Type,
  upload: Upload,
  user: User,
  users: Users,
  volume: Volume2,
  wand: Wand2,
  x: X,
  zap: Zap,
} as const;

export type IconName = keyof typeof MAP;

export function Ic({
  name,
  size = 18,
  strokeWidth = 2.4,
  ...rest
}: { name: IconName; size?: number; strokeWidth?: number } & Omit<SVGProps<SVGSVGElement>, 'name'>) {
  const Cmp = MAP[name];
  return <Cmp size={size} strokeWidth={strokeWidth} aria-hidden="true" focusable="false" {...rest} />;
}

/** Minimal platform marks for the download buttons (lucide has no brand icons). */
export function WindowsMark({ size = 18, ...rest }: { size?: number } & SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" width={size} height={size} fill="currentColor" aria-hidden="true" focusable="false" {...rest}>
      <path d="M3 5.5 10.5 4.4v7.1H3V5.5zm0 13L10.5 19.6v-7.1H3v6zm8.5 1.2L21 21V12.5h-9.5v7.2zm0-15.4v7.2H21V3l-9.5 1.3z" />
    </svg>
  );
}

export function AndroidMark({ size = 18, ...rest }: { size?: number } & SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" width={size} height={size} fill="currentColor" aria-hidden="true" focusable="false" {...rest}>
      <path d="M17.6 9.5l1.6-2.8a.3.3 0 0 0-.5-.3l-1.6 2.8A8.9 8.9 0 0 0 12 7.6a8.9 8.9 0 0 0-5.1 1.6L5.3 6.4a.3.3 0 0 0-.5.3l1.6 2.8A7.9 7.9 0 0 0 4 15.6h16a7.9 7.9 0 0 0-2.4-6.1zM8.7 13.2a.8.8 0 1 1 0-1.6.8.8 0 0 1 0 1.6zm6.6 0a.8.8 0 1 1 0-1.6.8.8 0 0 1 0 1.6zM4 16.6h16v3.6a1.4 1.4 0 0 1-1.4 1.4H5.4A1.4 1.4 0 0 1 4 20.2v-3.6z" />
    </svg>
  );
}

export function AppleMark({ size = 18, ...rest }: { size?: number } & SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" width={size} height={size} fill="currentColor" aria-hidden="true" focusable="false" {...rest}>
      <path d="M16.7 12.9c0-2.2 1.8-3.3 1.9-3.4-1-1.5-2.6-1.7-3.2-1.7-1.4-.1-2.7.8-3.3.8-.7 0-1.7-.8-2.9-.8-1.5 0-2.9.9-3.6 2.2-1.6 2.7-.4 6.7 1.1 8.9.7 1.1 1.6 2.3 2.8 2.2 1.1 0 1.5-.7 2.9-.7 1.3 0 1.7.7 2.9.7 1.2 0 2-1.1 2.7-2.2.9-1.3 1.2-2.5 1.3-2.6-.1 0-2.4-.9-2.4-3.6zM14.6 5.7c.6-.8 1-1.8.9-2.9-.9 0-2 .6-2.6 1.4-.6.7-1.1 1.8-1 2.8 1 .1 2-.5 2.7-1.3z" />
    </svg>
  );
}
